#!/bin/bash

menu(){
  echo " "
  echo "Manas: an opinionated setup for Debian Mate"
  echo " "
  echo "Usage: manas COMMAND [APP NAME] "
  echo " "
  echo "Commands:"
  echo "install-all    Installs all apps and settings."
  echo "uninstall-all  Uninstalls all apps and settings."
  echo "update-apps    Update apps without a repo"
  echo "install        Install individual app. Takes app name as argument"
  echo "uninstall      Uninstall individual app. Takes app name as argument."
  echo "update         Update individual app. Takes app name as argument."
  echo " "
}

install-all(){
  bash run-commands/install-all.sh
}

uninstall-all(){
  bash run-commands/uninstall-all.sh
}

# update apps without a repository
update-apps(){
  bash audio-video/freetube/update.sh
  bash accessories/localsend/update.sh
  bash graphics/drawio/update.sh
  bash audio-video/ytdownloader/update.sh
  bash office/marktext/update.sh
  bash databases/dbgate/update.sh
  bash accessories/ulauncher/update.sh
  bash office/sejdapdf/update.sh
}

app(){
  if [ -d accessories/$1 ]; then echo "accessories/$1" ; fi
  if [ -d audio-video/$1 ]; then echo "audio-video/$1" ; fi
  if [ -d databases/$1 ]; then echo "databases/$1" ; fi
  if [ -d development/$1 ]; then echo "development/$1" ; fi
  if [ -d graphics/$1 ]; then echo "graphics/$1" ; fi
  if [ -d office/$1 ]; then echo "office/$1" ; fi
  if [ -d programming-languages/$1 ]; then echo "programming-languages/$1" ; fi
  if [ -d system/$1 ]; then echo "system/$1" ; fi
  if [ -d web-browsers/$1 ]; then echo "web-browsers/$1" ; fi
}

install(){
  appname=$(app $1)
  bash $appname/install.sh
}

uninstall(){
  appname=$(app $1)
  bash $appname/uninstall.sh
}

update(){
  appname=$(app $1)
  bash $appname/update.sh
}

# show menu if there's no arguments
if [ $# -eq 0 ]; then menu; fi

# commands
if [ "$1" = "install-all" ]; then install-all; fi
if [ "$1" = "uninstall-all" ]; then uninstall-all; fi
if [ "$1" = "update-apps" ]; then update-apps 2> /tmp/manas.log ; fi
if [ "$1" = "install" ]; then install $2; fi
if [ "$1" = "uninstall" ]; then uninstall $2; fi
if [ "$1" = "update" ]; then update $2; fi
