#!/bin/bash

# apt updates  
sudo apt update
sudo apt full-upgrade -y
sudo apt autoremove -y

# update flatpaks and cleanup unused
flatpak uninstall --unused --delete-data -y
flatpak update -y

# update firmware
fwupdmgr refresh --force
fwupdmgr update


cd ~/.local/share/manas

# update direct-download apps
./manas update-apps 

# update manas
git pull

cd -
