#!/bin/bash

# prompt for sudo first
sudo echo -n ""

echo -e $(tput setaf 3)Updates from Debian repos $(tput setaf 7)
sudo apt update
sudo apt full-upgrade -y
sudo apt autoremove -y

echo -e $(tput setaf 3)Delete unused Flatpaks $(tput setaf 7)
flatpak uninstall --unused --delete-data -y

echo -e $(tput setaf 3)Update Flatpaks $(tput setaf 7)
flatpak update -y

echo -e $(tput setaf 3)Update Firmware $(tput setaf 7)
fwupdmgr refresh --force
fwupdmgr update


cd ~/.local/share/manas

echo -e $(tput setaf 3)Update direct-download apps $(tput setaf 7)
./manas update-apps 

echo -e $(tput setaf 3)Update Manas $(tput setaf 7)
git pull

cd -
