# uninstall unused packages
sudo apt-get purge -y \
  fonts-noto \
  gnome-keyring \
  seahorse \
  firefox-esr* \
  libreoffice* \
  gimp* \
  goldendict \
  mlterm \
  mlterm-tiny \
  xterm \
  xiterm+thai \
  orca \
  mate-applet-brisk-menu \
  mate-applets \
  mate-utils \
  mate-user-guide \
  synaptic \
  tasksel \
  ibrazilian \
  ibulgarian \
  icatalan \
  idanish \
  idutch \
  ifrench-gut \
  ifrench \
  ihungarian \
  iitalian \
  ilithuanian \
  ingerman \
  inorwegian \
  ipolish \
  iportuguese \
  irussian \
  ispanish \
  iswiss \
  wbrazilian \
  wbulgarian \
  wcatalan \
  wdanish \
  wdutch \
  wfrench \
  witalian \
  wngerman \
  wnorwegian \
  wpolish \
  wportuguese \
  wspanish \
  wswedish \
  myspell-eo \
  myspell-es \
  myspell-et \
  myspell-fa \
  myspell-ga \
  myspell-he \
  myspell-nb \
  myspell-nn \
  myspell-sk \
  myspell-sq \
  aspell-am \
  aspell-ar-large \
  aspell-ar \
  aspell-bg \
  aspell-ca \
  aspell-cs \
  aspell-cy \
  aspell-da \
  aspell-de \
  aspell-el \
  aspell-eo \
  aspell-es \
  aspell-et \
  aspell-eu \
  aspell-fa \
  aspell-fr \
  aspell-ga \
  aspell-gl-minimos \
  aspell-he \
  aspell-hr \
  aspell-hu \
  aspell-is \
  aspell-it \
  aspell-kk \
  aspell-ku \
  aspell-lt \
  aspell-lv \
  aspell-nl \
  aspell-no \
  aspell-pl \
  aspell-pt-br \
  aspell-pt-pt \
  aspell-ro \
  aspell-ru \
  aspell-sk \
  aspell-sl \
  aspell-sv \
  aspell-tl \
  hunspell-ar \
  hunspell-be \
  hunspell-bg \
  hunspell-bs \
  hunspell-ca \
  hunspell-cs \
  hunspell-da \
  hunspell-de-at \
  hunspell-de-ch \
  hunspell-de-de \
  hunspell-el \
  hunspell-eu \
  hunspell-fr-classical \
  hunspell-fr \
  hunspell-gl-es \
  hunspell-gl \
  hunspell-gu \
  hunspell-hi \
  hunspell-hr \
  hunspell-hu \
  hunspell-id \
  hunspell-is \
  hunspell-it \
  hunspell-kk \
  hunspell-kmr \
  hunspell-ko \
  hunspell-lt \
  hunspell-lv \
  hunspell-ml \
  hunspell-ne \
  hunspell-nl \
  hunspell-pl \
  hunspell-pt-br \
  hunspell-pt-pt \
  hunspell-ro \
  hunspell-ru \
  hunspell-si \
  hunspell-sl \
  hunspell-sr \
  hunspell-sv-se \
  hunspell-sv \
  hunspell-te \
  hunspell-th \
  hunspell-vi

sudo apt-get autoremove -y

sudo apt-get autoclean -y

# delete residual config files
dpkg -l | grep '^rc' | awk '{print $2}' | xargs sudo apt-get purge -y
